#!/usr/bin/env bash
# transfers file from client to server

if [ "$2" ==  "" -o "$3" == ""  ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi

path_out="$1"
user="$3"
ip="$2"
path_to_priv_key="$4"

scp -i "$path_to_priv_key" -o StrictHostKeyChecking=no  "$path_out" "$user@$ip:~/"
