#!/usr/bin/env bash
# installs nginx listening at port 80
# when sent a GET request at it's root, sends the response "Holberton School"
sudo apt-get update
apt update -y && apt upgrade -y
apt install nginx -y
echo "Holberton School" >/var/www/html/index.nginx-debian.html
service nginx restart
