#!/usr/bin/env bash
# Installs and configures haproxy on a load balance server
sudo apt-get update
sudo add-apt-repository -y ppa:vbernat/haproxy-2
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install -y  haproxy

echo ENABLED=1 | sudo tee /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 2689-web-01 35.185.20.113 check
    server 2689-web-02 34.75.130.100:80 check
" >> sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
