#!/usr/bin/env bash
# Configure the server to enable Nginx on 80 port

sudo rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
