#!/usr/bin/env bash
#set n to 1
n=1

#continue until $n equals 100
while [ $n -le 100 ]
do
   if  [ $((n % 5)) == 0 ] && [ $((n % 3)) == 0 ]
   then 
        echo "FizzB"
   
   elif [ $((n % 3)) == 0 ]
   then
        echo "Fizz"

   elif [ $((n % 5)) == 0 ]
   then
        echo "Buzz"

   else
        echo "$n"
    fi
   n=$((n + 1)) #increments $n
done
