#!/usr/bin/env bash
#set n to 1
n=1

#continue until $n equals 10
while [ $n -le 10 ]
do
   if  [ $n -eq 9 ]
   then 
        echo "Holberton School"
        echo "Hi"
    else
        echo "Holberton School"
   fi
   n=$((n + 1)) #increments $n
done
