#!/usr/bin/env bash
#set n to 1
n=1
 
#continue until $n equals 12
while [ $n -le 12 ]
do
   echo "Hour: $n"
   i=1
   while [ $i -lt 60 ]
   do
        echo "$i"
        i=$((i + 1)) 
    done

   n=$((n + 1)) #increments $n
done
